export const data = [
        {
            companyName: 'Hays',
            industry: 'Staffing & Recruiting',
            location: 'England, United Kingdom',
            country: 'United Kingdom',
            region: 'EMEA',
            city: 'London',
            ownershipType: 'Public',
            revenueSize: '$2B',
            revenueRange: '$1B - $5B',
            numberOfEmployees: '28,000',
            marketYear: '2024',
            grade: 'G7',
            jobFunction: 'HR',
            jobLevel: 'Manager',
            jobSubFunction: 'Talent Acquisition',
            marketIdentifier: 'UK-HAYS',
            p10: '2000',
            p25: '3000',
            p50: '4000',
            p75: '5000',
            p90: '6000',
            avgMonthly: '4200',
            targetMarketMonthly: '4500'
        },
        {
            companyName: 'TASC Outsourcing',
            industry: 'Staffing & Recruiting',
            location: 'Dubai, UAE',
            country: 'United Arab Emirates',
            region: 'MEA',
            city: 'Dubai',
            ownershipType: 'Private',
            revenueSize: '$200M',
            revenueRange: '$100M - $300M',
            numberOfEmployees: '1,200',
            marketYear: '2024',
            grade: 'G6',
            jobFunction: 'Recruiting',
            jobLevel: 'Specialist',
            jobSubFunction: 'Contract Staffing',
            marketIdentifier: 'UAE-TASC',
            p10: '1500',
            p25: '2200',
            p50: '3000',
            p75: '3700',
            p90: '4200',
            avgMonthly: '3100',
            targetMarketMonthly: '3300'
        },
        {
            companyName: 'NES Fircroft',
            industry: 'Staffing & Recruiting',
            location: 'Altrincham, United Kingdom',
            country: 'United Kingdom',
            region: 'EMEA',
            city: 'Altrincham',
            ownershipType: 'Private',
            revenueSize: '$500M',
            revenueRange: '$300M - $700M',
            numberOfEmployees: '3,300',
            marketYear: '2024',
            grade: 'G6',
            jobFunction: 'HR',
            jobLevel: 'Analyst',
            jobSubFunction: 'Operations',
            marketIdentifier: 'UK-NES',
            p10: '1900',
            p25: '2700',
            p50: '3500',
            p75: '4300',
            p90: '5000',
            avgMonthly: '3600',
            targetMarketMonthly: '3800'
        },
        {
            companyName: 'Sundus',
            industry: 'Human Resources',
            location: 'Abu Dhabi, UAE',
            country: 'United Arab Emirates',
            region: 'MEA',
            city: 'Abu Dhabi',
            ownershipType: 'Private',
            revenueSize: '$100M',
            revenueRange: '$50M - $150M',
            numberOfEmployees: '540',
            marketYear: '2024',
            grade: 'G5',
            jobFunction: 'Operations',
            jobLevel: 'Executive',
            jobSubFunction: 'Admin',
            marketIdentifier: 'UAE-SUNDUS',
            p10: '1200',
            p25: '1900',
            p50: '2700',
            p75: '3500',
            p90: '4100',
            avgMonthly: '2800',
            targetMarketMonthly: '3000'
        },
        {
            companyName: 'Robert Half',
            industry: 'Staffing & Recruiting',
            location: 'Menlo Park, California',
            country: 'USA',
            region: 'North America',
            city: 'Menlo Park',
            ownershipType: 'Public',
            revenueSize: '$5B',
            revenueRange: '$4B - $6B',
            numberOfEmployees: '28,000',
            marketYear: '2024',
            grade: 'G8',
            jobFunction: 'Finance',
            jobLevel: 'Director',
            jobSubFunction: 'Audit',
            marketIdentifier: 'US-RH',
            p10: '2500',
            p25: '3500',
            p50: '4600',
            p75: '5800',
            p90: '7000',
            avgMonthly: '4900',
            targetMarketMonthly: '5100'
        },
        {
            companyName: 'Dulsco Group',
            industry: 'Staffing & Recruiting',
            location: 'Dubai, UAE',
            country: 'United Arab Emirates',
            region: 'MEA',
            city: 'Dubai',
            ownershipType: 'Private',
            revenueSize: '$300M',
            revenueRange: '$200M - $400M',
            numberOfEmployees: '4,600',
            marketYear: '2024',
            grade: 'G6',
            jobFunction: 'Recruiting',
            jobLevel: 'Associate',
            jobSubFunction: 'Staffing',
            marketIdentifier: 'UAE-DULSCO',
            p10: '1700',
            p25: '2500',
            p50: '3400',
            p75: '4200',
            p90: '4900',
            avgMonthly: '3600',
            targetMarketMonthly: '3800'
        }
    ];